ugv_nav4d_ros2:
  ros__parameters:
    read_cloud_from_ply: false
    read_pose_from_topic: true
    map_ply_path: 'path to ply file'
    mls_gap_size: 0.1
    robot_frame: husky/base_link
    world_frame: map
    grid_resolution: 0.5
    grid_max_x: 100
    grid_min_x: -100
    grid_max_y: 100
    grid_min_y: -100
    dumpOnError: false
    dumpOnSuccess: false
    initialPatchRadius: 3.0
    #Mobility Parameters
    maxMotionCurveLength: 100.0
    minTurningRadius: 0.8
    multiplierBackward: 2.0
    multiplierBackwardTurn: 3.0
    multiplierForward: 1.0
    multiplierForwardTurn: 2.0
    multiplierLateral: 4.0
    multiplierLateralCurve: 4.0
    multiplierPointTurn: 2.0
    rotationSpeed: 1.0
    searchProgressSteps: 0.1
    searchRadius: 1.0
    translationSpeed: 1.0   
    spline_sampling_resolution: 0.05
    remove_goal_offset: false
    #Planner Parameters
    epsilonSteps: 2
    initialEpsilon: 64
    numThreads: 8
    planningTime: 500000000
    #Motion Primitive Parameters:
    cellSkipFactor: 0.1
    destinationCircleRadius: 6
    generateBackwardMotions: true
    generateForwardMotions: true
    generateLateralMotions: false
    generatePointTurnMotions: false
    numAngles: 16
    numEndAngles: 8
    splineOrder: 4
    #Traversability Parameters:
    allowForwardDownhill: true
    costFunctionDist: 0.0
    distToGround: 0.0
    enableInclineLimitting: false
    inclineLimittingLimit: 0.1
    inclineLimittingMinSlope: 0.2
    initialPatchVariance: 0.0001
    maxSlope: 0.45
    maxStepHeight: 0.25
    minTraversablePercentage: 0.4
    robotHeight: 1.0
    robotSizeX: 1.2
    robotSizeY: 0.8
    slopeMetric: :NONE
    slopeMetricScale: 1.0