#!/usr/bin/env python3
"""Subscribe to a PointCloud2 topic and save the received cloud(s) as PLY.

    ros2 run ugv_nav4d_ros2 pc2_to_ply.py /ouster/points
    ros2 run ugv_nav4d_ros2 pc2_to_ply.py /ouster/points -o cloud.ply --count 5 --ascii

Saves the first cloud (or --count clouds, numbered _000, _001, ...) and
exits. XYZ is always written; intensity and rgb are carried over when the
topic has them. The subscriber mirrors the publisher's QoS, so it works on
best-effort sensor streams AND on latched (transient_local) map topics like
/slam3d/map, where the one existing message is delivered on connect.
"""

import argparse
import os
import sys
import time

import numpy as np
import rclpy
from rclpy.node import Node
from rclpy.qos import (DurabilityPolicy, HistoryPolicy, QoSProfile,
                       ReliabilityPolicy)
from sensor_msgs.msg import PointCloud2
from sensor_msgs_py import point_cloud2


def save_ply(path, cloud, ascii_mode):
    """cloud: structured array with x/y/z and optionally intensity/rgb columns."""
    names = cloud.dtype.names
    has_intensity = 'intensity' in names
    has_rgb = 'rgb' in names

    out_dtype = [('x', '<f4'), ('y', '<f4'), ('z', '<f4')]
    if has_intensity:
        out_dtype.append(('intensity', '<f4'))
    if has_rgb:
        out_dtype += [('red', 'u1'), ('green', 'u1'), ('blue', 'u1')]
    out = np.empty(cloud.shape[0], dtype=out_dtype)
    for axis in ('x', 'y', 'z'):
        out[axis] = cloud[axis].astype(np.float32)
    if has_intensity:
        out['intensity'] = cloud['intensity'].astype(np.float32)
    if has_rgb:
        rgb = np.ascontiguousarray(cloud['rgb'])
        packed = rgb.view(np.uint32) if rgb.dtype == np.float32 else rgb.astype(np.uint32)
        out['red'] = (packed >> 16) & 0xFF
        out['green'] = (packed >> 8) & 0xFF
        out['blue'] = packed & 0xFF

    header = ['ply',
              'format {} 1.0'.format('ascii' if ascii_mode else 'binary_little_endian'),
              'comment generated by pc2_to_ply.py',
              'element vertex {}'.format(out.shape[0]),
              'property float x',
              'property float y',
              'property float z']
    if has_intensity:
        header.append('property float intensity')
    if has_rgb:
        header += ['property uchar red', 'property uchar green', 'property uchar blue']
    header.append('end_header')

    with open(path, 'wb') as f:
        f.write(('\n'.join(header) + '\n').encode('ascii'))
        if ascii_mode:
            fmt = ' '.join(['%.6f'] * (3 + (1 if has_intensity else 0)) +
                           ['%d'] * (3 if has_rgb else 0))
            np.savetxt(f, np.stack([out[n].astype(np.float64) for n in out.dtype.names], axis=1),
                       fmt=fmt)
        else:
            out.tofile(f)


class Pc2ToPly(Node):
    def __init__(self, args):
        super().__init__('pc2_to_ply')
        self.args = args
        self.saved = 0
        self.done = False
        self.subscription = None
        self._probe_timer = self.create_timer(0.5, self._probe)
        self.get_logger().info('Waiting for a publisher on {} ...'.format(args.topic))
        self._probe()

    def _probe(self):
        if self.subscription is not None or self.done:
            return
        infos = self.get_publishers_info_by_topic(self.args.topic)
        if not infos:
            return
        types = {i.topic_type for i in infos}
        if 'sensor_msgs/msg/PointCloud2' not in types:
            self.get_logger().error(
                '{} is of type {}, not sensor_msgs/msg/PointCloud2.'.format(
                    self.args.topic, ', '.join(sorted(types))))
            self.done = True
            return
        # Mirror the publisher QoS. A transient_local subscription is the only
        # way to receive a latched map published before this node started, but
        # it refuses to match a volatile publisher, so only request it when
        # every publisher offers it. Reliable delivery likewise only when no
        # publisher is best-effort.
        reliability = (ReliabilityPolicy.BEST_EFFORT
                       if any(i.qos_profile.reliability == ReliabilityPolicy.BEST_EFFORT
                              for i in infos)
                       else ReliabilityPolicy.RELIABLE)
        durability = (DurabilityPolicy.TRANSIENT_LOCAL
                      if all(i.qos_profile.durability == DurabilityPolicy.TRANSIENT_LOCAL
                             for i in infos)
                      else DurabilityPolicy.VOLATILE)
        qos = QoSProfile(history=HistoryPolicy.KEEP_LAST, depth=5,
                         reliability=reliability, durability=durability)
        self.subscription = self.create_subscription(
            PointCloud2, self.args.topic, self.callback, qos)
        self._probe_timer.cancel()
        self.get_logger().info('Publisher found ({}, {}); waiting for a cloud on {} ...'.format(
            reliability.name.lower(), durability.name.lower(), self.args.topic))

    def output_path(self):
        path = self.args.output
        if not path:
            stem = self.args.topic.strip('/').replace('/', '_') or 'cloud'
            path = '{}_{}.ply'.format(stem, time.strftime('%Y%m%d_%H%M%S'))
        if self.args.count > 1:
            root, ext = os.path.splitext(path)
            path = '{}_{:03d}{}'.format(root, self.saved, ext or '.ply')
        return path

    def callback(self, msg):
        if self.done:
            return
        available = [f.name for f in msg.fields]
        wanted = [n for n in ('x', 'y', 'z', 'intensity', 'rgb') if n in available]
        if not all(n in wanted for n in ('x', 'y', 'z')):
            self.get_logger().error(
                'Topic has no x/y/z fields (found: {}); cannot save.'.format(available))
            self.done = True
            return
        cloud = point_cloud2.read_points(msg, field_names=wanted, skip_nans=False)
        cloud = np.asarray(cloud).reshape(-1)
        finite = (np.isfinite(cloud['x']) & np.isfinite(cloud['y']) &
                  np.isfinite(cloud['z']))
        cloud = cloud[finite]
        if cloud.shape[0] == 0:
            self.get_logger().warning('Received a cloud with no finite points; waiting for the next one.')
            return
        path = self.output_path()
        save_ply(path, cloud, self.args.ascii)
        self.saved += 1
        self.get_logger().info('Saved {} point(s) to {} ({}/{})'.format(
            cloud.shape[0], os.path.abspath(path), self.saved, self.args.count))
        if self.saved >= self.args.count:
            self.done = True


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('topic', help='PointCloud2 topic to subscribe to')
    parser.add_argument('-o', '--output', default=None,
                        help='output .ply path (default: <topic>_<timestamp>.ply)')
    parser.add_argument('--count', type=int, default=1,
                        help='number of clouds to save before exiting (default: 1)')
    parser.add_argument('--ascii', action='store_true',
                        help='write ASCII PLY instead of binary (bigger, human-readable)')
    args, ros_args = parser.parse_known_args()

    rclpy.init(args=sys.argv[:1] + ros_args)
    node = Pc2ToPly(args)
    try:
        while rclpy.ok() and not node.done:
            rclpy.spin_once(node, timeout_sec=0.2)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()
    return 0 if node.saved >= args.count else 1


if __name__ == '__main__':
    sys.exit(main())
